server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;


    location /Article {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # These headers tell the backend the real client IP, not nginx's IP
    }


    location / {
        try_files $uri $uri/ /index.html;
    }
}