// <auto-generated />
using Lexicon.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lexicon.Migrations
{
    [DbContext(typeof(LexiconDbContext))]
    [Migration("20260608000000_SoftDeleteUsers")]
    partial class SoftDeleteUsers
    {
    }
}
